### ISSUE TITLE
Changes in timedate and _

### ISSUE THREAD

**Issue by cbho** [foxcris/appdaemon-blinds-control#1]
Any chance you're working on an update that's adapted to the changes that was implemented on `timedate` and the use of _ in names?
Looks really cool and would love to use your app ;-)

**Comment by foxcris** [comment]
Hi,

thanks for your request. I would like to help you but currently i am not sure what you are talking about.
Could you please give me an hint about what changes on timedate you are talking? 
What's the issue you have with _ in names?

**Comment by cbho** [comment]
[Release 0.86](https://www.home-assistant.io/blog/2019/01/23/release-86/):
"Another noteworthy breaking change (sorry!), is that the automation time trigger has been split into two: time and time_pattern. If you had a time trigger containing the keys hours, minutes or seconds, update the platform from time to time_pattern.

Guess this is why it looks like this in my setup:
![image](https://user-images.githubusercontent.com/29979509/52216893-94046700-2897-11e9-9bf7-254cbc0d02b7.png)

Regarding underscores:
One of the groups made in the output file `config_blinds.yaml_` is named - `group.config_blinds_config_blinds_` (given it is only one group, it's not a big deal to rename it (and perhaps i bit misleading that I wrote "names" given it is only one name - my apologies ;-) )

**Comment by foxcris** [comment]
Hi,

regarding your issue with invalid date. I don'T think thats related to the bracking change in 0.86. I am already running 0.86.4 and in my setup everything just works fine:
![setup_kitchen_level](https://user-images.githubusercontent.com/361299/52237728-a0ee7e00-28ca-11e9-9f77-a04a314c139e.PNG)

After setting up everything for the first time you have to click on "invalid date" and configure the time you want to set. Your configured time should then be stored by the home-assistant [recoder component]https://www.home-assistant.io/components/recorder/](https://www.home-assistant.io/components/recorder/). 

Regarding the name of the entitiy "group.config_blinds_config_blinds_". I will take a look at it.

**Comment by cbho** [comment]
That did the trick - sorry, didn't think about the option to click on "invalid date" - but it does exactly as you say - thank you :-)
