### ISSUE TITLE
Targeting "all devices" broken

### ISSUE THREAD

**Issue by cbho** [foxcris/appdaemon-blinds-control#2]
Got the app up and running - but get this error messsage:
`Not passing an entity ID to a service to target all entities is deprecated. Use instead: entity_id: "all"`

(The downside of hass - breaking changes in almost each release)

**Comment by foxcris** [comment]
Hi,

where do you see the error? All my logic is done in appdaemon. The part in hass is only providing the switches and time field to configure the behaviour.

Your error looks like an scripting error in hass itself which should be independent from my blinds control.

Perhaps you can send the the logfile of appdaemon?
